name: Release Build (Test)

on:
  workflow_dispatch: # Позволяет запустить вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4

      - name: Генерируем моковые бинарники
        run: |
          mkdir -p build/linux/gcc/x86_64/bin/
          echo "This is a test binary 1" > build/linux/gcc/x86_64/bin/mock-binary-1
          echo "This is a test binary 2" > build/linux/gcc/x86_64/bin/mock-binary-2
          chmod +x build/linux/gcc/x86_64/bin/*

      - name: Загружаем моковые бинарники как артефакты
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries
          path: build/linux/gcc/x86_64/bin/*
          retention-days: 7

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4

      - name: Загружаем бинарники из артефактов
        uses: actions/download-artifact@v4
        with:
          name: release-binaries
          path: binaries

      - name: Генерируем changelog
        id: changelog
        run: |
          {
            echo "changelog<<EOF"
            git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s (%h)" || echo "No changes"
            echo "EOF"
          } >> $GITHUB_ENV


      - name: Создать тестовый релиз с моковыми бинарниками
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "test-release-${{ github.run_id }}"
          name: "Test Release ${{ github.run_id }}"
          body: |
            🚀 Тестовый релиз ${{ github.run_id }}!
            
            ### Changelog
            ${{ env.changelog }}
          draft: true
          prerelease: true
          files: binaries/*
